/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


  class JSI_EXPORT NativeRealPathCxxSpecJSI : public TurboModule {
protected:
  NativeRealPathCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

public:
  virtual jsi::String getPath(jsi::Runtime &rt, jsi::String path) = 0;

};

template <typename T>
class JSI_EXPORT NativeRealPathCxxSpec : public TurboModule {
public:
  jsi::Value get(jsi::Runtime &rt, const jsi::PropNameID &propName) override {
    return delegate_.get(rt, propName);
  }

  static constexpr std::string_view kModuleName = "RealPath";

protected:
  NativeRealPathCxxSpec(std::shared_ptr<CallInvoker> jsInvoker)
    : TurboModule(std::string{NativeRealPathCxxSpec::kModuleName}, jsInvoker),
      delegate_(reinterpret_cast<T*>(this), jsInvoker) {}


private:
  class Delegate : public NativeRealPathCxxSpecJSI {
  public:
    Delegate(T *instance, std::shared_ptr<CallInvoker> jsInvoker) :
      NativeRealPathCxxSpecJSI(std::move(jsInvoker)), instance_(instance) {

    }

    jsi::String getPath(jsi::Runtime &rt, jsi::String path) override {
      static_assert(
          bridging::getParameterCount(&T::getPath) == 2,
          "Expected getPath(...) to have 2 parameters");

      return bridging::callFromJs<jsi::String>(
          rt, &T::getPath, jsInvoker_, instance_, std::move(path));
    }

  private:
    friend class NativeRealPathCxxSpec;
    T *instance_;
  };

  Delegate delegate_;
};

} // namespace facebook::react
